avance2/materiales3c-main/api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [

]

avance2/materiales3c-main/cdplaest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('core/', include("core.urls")),
    path('', include("home.urls")),

]

avance2/materiales3c-main/core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="gg_list"), 
    #en path se utilizan siempre 3 parametros
]

avance2/materiales3c-main/home/urls.py
from django.urls import path

from home import views

app_name = "home"

urlpatterns = [
        path('', views.Index.as_view(), name="index"),
        path('about/', views.About.as_view(), name="about"),
        path('identity', views.Identity.as_view(), name="identity"),
        path('contacto', views.Contacto.as_view(), name="contacto"),
    ]

avance2/materiales3c-main/api/models.py
from django.db import models

# Create your models here.

avance2/materiales3c-main/core/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

    ### GRANT GOALS ####
# Base de datos

STATE_CHOICES = (
        ('Done', 'DN'),
        ('Doing', 'DG'),
        ('Not Stared', 'NS'),
)

class GrantGoal(models.Model):
            user = models.ForeignKey(User, on_delete=models.CASCADE)

            gg_tittle = models.CharField(max_length=128, default="Generic Grant Goal Tittle")
            # Charfield es el varchar del mysql
            description= models.CharField(max_length=256, default="Generic Grant Goal Description")

            timestamp = models.DateField(auto_now_add=True)
            days_duration = models.IntegerField(default=7)
            final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
            # Este campo va a ser calculado, y dice que no tome del servideo la fecha de actualizacion. y que puede estar en blanco y vacio
            status = models.BooleanField(default=True)
            state = models.CharField(max_length=16, choices=STATE_CHOICES)
            # El choices, nos permite elejir de una lista de elemneto un elemento para el campo   
            sprint = models.IntegerField(default=1) #Avances a mostrar en el objetivo
            slug = models.SlugField(max_length=16) #Campo extra, el cual puede dar la respuesta con menor cantidad de caracteres
            

            def __str__(self):
                    return self.gg_tittle
            # Regresa el titulo



    #  #### GOALS ####
    # ### SUBGOALS ####
    # ### ISSUES ####

avance2/materiales3c-main/home/models.py
from django.db import models

# Create your models here.

avance2/materiales3c-main/api/views.py
from django.shortcuts import render

# Create your views here.

avance2/materiales3c-main/core/views.py
from django.shortcuts import render
from django.views import generic

from .models import GrantGoal

# Create your views here.

class ListGrantGoal(generic.View):
    template_name = "core/gg_list.html"
    context = {}


# Se instancia la clase para poner atributos
    def get(self, request, *args, **kwargs):
        queryset = GrantGoal.objects.filter(status=True) #consulta que lleva where
        self.context = {
            "grant_goals" : queryset
        }
        return render(request, self.template_name, self.context)
    
    # def para consultar
    # get para obtener

avance2/materiales3c-main/home/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.

class Index(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Gerardo Aguilar",
            "lista": [1, 2, 3]

        }
        return render(request, self.template_name, self.context)
    


    


# Ahorrador de html

class About(generic.View):
    template_name = "home/about.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Gerardo Aguilar"
        }
        return render(request, self.template_name, self.context)
    


class Identity(generic.View):
    template_name = "home/identity.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Gerardo Aguilar"
        }
        return render(request, self.template_name, self.context)
    



class Contacto(generic.View):
    template_name = "home/contacto.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Gerardo Aguilar"
        }
        return render(request, self.template_name, self.context)
    

avance2/materiales3c-main/templates/base/base.html
{%load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block tittle %}{%endblock tittle %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

   

    
  </head>
<body>
  <div id="bienvenido-izquierda" style="float: left;">Bienvenido</div>
  <div id="bienvenido-derecha" style="float: right;">Bienvenido</div>

  
  <div class="container">
    <div class="row">
      <div class="col">

        <nav class="navbar navbar-expand-lg" style="background-color: darkorange;">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">MENU</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}" style="color: white;">INICIO</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:about' %}" style="color: white;">About</a>
                </li>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:contacto' %}" style="color: white;">contacto</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: white;">
                    Dropdown
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#" style="color: rgb(255, 119, 0);">Materiales</a></li>
                    <li><a class="dropdown-item" href="#" style="color: rgb(255, 119, 0);">Herramientas</a></li>
                    <li><a class="dropdown-item" href="#" style="color: rgb(255, 98, 0);">Dinero</a></li>
                </ul>
            </li>
            
            </li>
            
              </ul>
            </div>
          </div>
        </nav>
        
        
      </div>
    </div>
    <div class="row">
      <div class="col">

      </div>
      <div>
      {% comment %} <div class="col -18"> {% endcomment %}
        {%block content %}

        {%endblock content %}

        <br>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tu Página de Materiales de Construcción</title>
        <style>
            /* Estilos para la barra de menú */
            .menu {
                background-color: white; /* Fondo blanco */
                padding: 10px;
            }
    
            .menu ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                display: flex;
                justify-content: center;
            }
    
            .menu li {
                margin: 0 15px;
            }
    
            .menu a {
                text-decoration: none;
                color: #333; /* Color de texto gris oscuro */
                font-weight: bold;
            }
    
            .menu a:hover {
                color: #007bff; /* Color de texto azul al pasar el mouse */
            }
        </style>
    </head>
    <body>
        <div class="menu">
            <ul>
                
                <li><a href="#">Materiales</a></li>
                <li><a href="#">Herramientas</a></li>
                <li><a href="#">Ofertas</a></li>
                
            </ul>
        </div>
        <br>
      </div>



    </div>
    
    </div>


  </div>

        <!-- Remove the container if you want to extend the Footer to full width. -->
{% comment %} <div class="container my-5"> {% endcomment %}
<div class="my-18 "> 
  <footer class="bg-dark text-center text-lg-start text-white ">
    <!-- Grid container -->
    <div class="container p-4">
      <!--Grid row-->
      <div class="row mt-4">
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">CONTACTO</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white"><i class="fas fa-book fa-fw fa-sm me-2"></i>Bestsellers</a>
              <img src="" alt="">

            </li>
            <li>
              <a href="#!" class="text-white"><i class="fas fa-book fa-fw fa-sm me-2"></i>All books</a>
            </li>
            <li>
              <a href="#!" class="text-white"><i class="fas fa-user-edit fa-fw fa-sm me-2"></i>Our authors</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">REDES SOCIALES</h5>
          <ul class="list-unstyled mb-0">
            <li>
              <a href="https://www.facebook.com/tu_pagina" class="text-white">
                <i class="fab fa-facebook fa-fw fa-sm me-2"></i>Facebook
              </a>
            </li>
            <li>
              <a href="https://twitter.com/tu_pagina" class="text-white">
                <i class="fab fa-twitter fa-fw fa-sm me-2"></i>Twitter
              </a>
            </li>
            <li>
              <a href="https://www.instagram.com/tu_pagina" class="text-white">
                <i class="fab fa-instagram fa-fw fa-sm me-2"></i>Instagram
              </a>
            </li>
          </ul>
        </div>
        

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Publishing house</h5>

          <ul class="list-unstyled">
            <li>
              <a href="#!" class="text-white">The BookStore</a>
            </li>
            <li>
              <a href="#!" class="text-white">123 Street</a>
            </li>
            <li>
              <a href="#!" class="text-white">05765 NY</a>
            </li>
            <li>
              <a href="#!" class="text-white"><i class="fas fa-briefcase fa-fw fa-sm me-2"></i>Send us a book</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Write to us</h5>

          <ul class="list-unstyled">
            <li>
              <a href="#!" class="text-white"><i class="fas fa-at fa-fw fa-sm me-2"></i>Help in purchasing</a>
            </li>
            <li>
              <a href="#!" class="text-white"><i class="fas fa-shipping-fast fa-fw fa-sm me-2"></i>Check the order status</a>
            </li>
            <li>
              <a href="#!" class="text-white"><i class="fas fa-envelope fa-fw fa-sm me-2"></i>Join the newsletter</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgb(238, 102, 18)">
      © 2021 Copyright:
      <a class="text-white" href="{% static 'css/bootstrap.min.css' %}">ELCONSTRUTOR.COM</a>
    </div>
    <!-- Copyright -->
  </footer>
</div>
{% comment %} </div> {% endcomment %}
<!-- End of .container -->

<script src="{% static 'js/boostrap/min.css' %}"></script>
      



      
</body>
</html>

<!-- Con los {%load static %} que estan en el archivo los paso pa todos, es herencia -->

avance2/materiales3c-main/templates/core/gg_list.html
{%extends 'base/base.html'%}

{%block tittle %} LIST GRANT GOAL VIEW {% endblock tittle%}

{% block content %}
<table class="table table-striped table-hover">
    <thead>
        <th>ID</th>
        <th>GG TITTLE</th>
        <th>TIMESTAMP</th>
        <th>DAYS DURING</th>
        <th>USER</th>
        <th></th>
        <th>ACTIONS</th>
        <th></th>
    </thead>
    <tbody>
        {% for gg in grant_goals %}
        <tr>
            <td>{{ gg.id }}</td>
            <td>{{ gg.gg_tittle }}</td>
            <td>{{ gg.timestamp }}</td>
            <td>{{ gg.days_during }}</td>
            <td>{{ gg.user }}</td>
            <td>{{ gg.gg_actions }}</td>
            <td><a href="" class="btn btn-outline-info">Detail</a></td>
            <td><a href="" class="btn btn-outline-warning">Update</a></td>
            <td><a href="" class="btn btn-outline-danger">Delete</a></td>
            
        </tr>
        {% endfor%}
    </tbody>
</table>

{% endblock content %}

avance2/materiales3c-main/templates/home/about.html
{% extends "base/base.html" %}
{% block tittle %} Index View {% endblock tittle %}

{%block content  %}
    <h1>Hey {{ name }}  Bienvenido seas to Django</h1>
    <button class="btn btn-outline-danger">Test Boostrao</button>

    {%endblock content %}

avance2/materiales3c-main/templates/home/contacto.html
{% extends "base/base.html" %}
{% block tittle %} Index View {% endblock tittle %}

{%block content  %}
    <h1>Hey {{ name }}  Bienvenido seas to Django</h1>
    <button class="btn btn-outline-danger">Test Boostrao</button>

    {%endblock content %}

avance2/materiales3c-main/templates/home/identity.html
{% extends "base/base.html" %}
{% block tittle %} Index View {% endblock tittle %}

{%block content  %}
    <h1>Hey {{ name }}  Bienvenido seas to Django</h1>
    <button class="btn btn-outline-danger">Test Boostrao</button>

    {%endblock content %}

avance2/materiales3c-main/templates/home/index.html
{% extends "base/base.html" %}
{% block tittle %} Index View {% endblock tittle %}

{%block content  %}

<!-- {% comment %} Lo siguiente son las imagenes deslizantes {% endcomment %} -->

<div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active" data-interval="10000">
        <img src="https://www.expertosupermastick.com/wp-content/uploads/2023/02/bodega-materiales-de-construccio%CC%81n.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item" data-interval="2000">
        <img src="https://realestatemarket.com.mx/images/2022/09-septiembre/0909/materiales-de-construccion-g.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
        <img src="https://www.expertosupermastick.com/wp-content/uploads/2023/02/bodega-materiales-de-construccio%CC%81n.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

    
    {%endblock content %}